import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import styles from "../styles/Home.module.css";

export default function Foo() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next Router sandbox</h1>

        <button onClick={() => router.push("/")}>Back</button>
      </main>
    </div>
  );
}
